// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCRMU48YnApxrGch2UGqyLc_ICiaLTUHY',
    appId: '1:1092505889742:web:22e1d7c495677dabfb999f',
    messagingSenderId: '1092505889742',
    projectId: 'evently2-3d592',
    authDomain: 'evently2-3d592.firebaseapp.com',
    storageBucket: 'evently2-3d592.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7sdydywL0nQrRwjUPsocn5D8R4JZ1Cso',
    appId: '1:1092505889742:android:83d60d56865e9ef7fb999f',
    messagingSenderId: '1092505889742',
    projectId: 'evently2-3d592',
    storageBucket: 'evently2-3d592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOdN8E-gclltUhuxLGwoGeNvLoTigKFI',
    appId: '1:1092505889742:ios:f1bbebfa27d4358afb999f',
    messagingSenderId: '1092505889742',
    projectId: 'evently2-3d592',
    storageBucket: 'evently2-3d592.firebasestorage.app',
    iosBundleId: 'com.example.evently2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOdN8E-gclltUhuxLGwoGeNvLoTigKFI',
    appId: '1:1092505889742:ios:f1bbebfa27d4358afb999f',
    messagingSenderId: '1092505889742',
    projectId: 'evently2-3d592',
    storageBucket: 'evently2-3d592.firebasestorage.app',
    iosBundleId: 'com.example.evently2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCRMU48YnApxrGch2UGqyLc_ICiaLTUHY',
    appId: '1:1092505889742:web:cbbf823f4a54364dfb999f',
    messagingSenderId: '1092505889742',
    projectId: 'evently2-3d592',
    authDomain: 'evently2-3d592.firebaseapp.com',
    storageBucket: 'evently2-3d592.firebasestorage.app',
  );
}
